apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: run-team
  namespace: eks
spec:
  version: 8.14.1
  count: 1
  elasticsearchRef:
    name: run-team
  http:
    tls:
      selfSignedCertificate:
        disabled: true