apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rootshell
  labels:
    app: rootshell
spec:
  selector:
    matchLabels:
      app: rootshell
  template:
    metadata:
      labels:
        app: rootshell
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - name: rootshell
        image: busybox
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host
          name: host
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
      volumes:
      - name: host
        hostPath:
          path: /
